[package]
name = "untgz"
version = "0.0.1"
edition = "2021"
author = "邱张华, <qiuzhanghua@gmail.com>"

[dependencies]
clap = { version = "4.5.26", features = ["derive", "unicode", "wrap_help"] }
flate2 = "1.0.35"
tar = "0.4.43"
tempfile = "3.15.0"
